name: Project Management

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, merged]

jobs:
  update-project:
    runs-on: ubuntu-latest
    name: Update Project Board
    
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/plv92/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update project status
        if: github.event.action == 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Issue or PR closed, updating project status to Done')
            // This would require additional logic to move items to "Done" column
            // Implementation depends on specific project board setup